name: pdf_reader
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  flutter_pdfview: ^1.3.2
  path: ^1.8.3
  uni_links: ^0.5.1
  uri_to_file: ^1.0.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
flutter:
  uses-material-design: true